[package]
name = "zed-stylelint"
version = "1.6.0"
edition = "2024"
license = "MIT"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
zed_extension_api = "0.7.0"
toml = "0.8"

serde = { version = "1.0", features = ["derive"] }
